### ISSUE TITLE
Milestone: Single Player MVP ("extermination")

### ISSUE THREAD

**Issue by TheNotary** [TriNetCo/pax-imperia-clone#19]
As a single player gamer, 

I need to be able to move my ship to an enemy sector,
and destroy enemy ships,
and demolish enemy colonies,
and view the Game Over screen,

to enjoy the game.  

### Features and Tasks:
- [ ] Create view to start a new single player game
- [ ] Feature: Basic ship controls
  - [ ] Create UI controls for ships
  - [ ] Enable moving a ship on the space view (scripting, UI button driven, and right click movement)
  - [ ] Enabled moving a ship from one system to another system
  - [ ] Destroy an enemy battle ship
  - [ ] Destroy an enemy planet
- [ ] Feature: Setup automated browser testing infrastructure
  - [ ] Research Browser test frameworks and report options
  - [ ] Decide on which browser testing framework to support
  - [ ] Configure the browser testing framework and write a test for the Single Player MVP
  - [ ] Add controls, triggers, and observability for browser test automation
    - Automate the browser test to run locally when a push is performed to main
    - Automate the browser test to run via Github Actions upon merges to master
    - Prevent merges to main until browser
    - Add badge to README.md so we can see when main is broken
- [ ] Create test suite that validates the correctness of the Single Player MVP implementation
- [ ] Feature: Victory Conditions - total annihilation
  - [ ] Create view for Game Over - Victory page
  - [ ] Implement marking a colonizer as "eliminated" in data structure
  - [ ] Implement Victory Conditions wherein when all other players are eliminated, end the game
